USE OOP_PC_INFO;
GO


CREATE OR ALTER PROCEDURE CREATE_RAM(
	@Type		NVARCHAR(15),
	@Volume		DECIMAL(15, 2)
)
AS
BEGIN
	INSERT INTO RAM(TYPE, VOLUME)
	VALUES (@Type, @Volume);
END;
GO

CREATE OR ALTER PROCEDURE UPDATE_RAM(
	@Id			INT,
	@Type		NVARCHAR(15),
	@Volume		DECIMAL(15, 2)
)
AS
BEGIN
	UPDATE RAM
	SET
		TYPE = ISNULL(@Type, TYPE),
		VOLUME = ISNULL(@Volume, VOLUME)
	WHERE ID = @Id;
END;
GO

CREATE OR ALTER PROCEDURE DELETE_RAM(
	@Id		INT
)
AS
BEGIN
	DELETE FROM RAM
	WHERE ID = @Id;
END;
GO


CREATE OR ALTER PROCEDURE CREATE_ROM(
	@Type		NVARCHAR(15),
	@Volume		DECIMAL(15, 2)
)
AS
BEGIN
	INSERT INTO ROM(TYPE, VOLUME)
	VALUES (@Type, @Volume);
END;
GO

CREATE OR ALTER PROCEDURE UPDATE_ROM(
	@Id			INT,
	@Type		NVARCHAR(15),
	@Volume		DECIMAL(15, 2)
)
AS
BEGIN
	UPDATE ROM
	SET
		TYPE = ISNULL(@Type, TYPE),
		VOLUME = ISNULL(@Volume, VOLUME)
	WHERE ID = @Id;
END;
GO

CREATE OR ALTER PROCEDURE DELETE_ROM(
	@Id		INT
)
AS
BEGIN
	DELETE FROM ROM
	WHERE ID = @Id;
END;
GO


CREATE OR ALTER PROCEDURE CREATE_CPU(
	@Manufacturer		NVARCHAR(15),
	@Series				NVARCHAR(15),
	@Model				NVARCHAR(15),
	@Cores				INT,
	@MaxFrequency		DECIMAL(15, 2),
	@WorkingFrequency	DECIMAL(15, 2),
	@Architecture		NVARCHAR(15)
)
AS
BEGIN
	INSERT INTO CPU(MANUFACTURER, SERIES, MODEL, CORES, MAX_FREQUENCY, WORKING_FREQUENCY, ARCHITECTURE)
	VALUES (@Manufacturer, @Series, @Model, @Cores, @MaxFrequency, @WorkingFrequency, @Architecture);
END;
GO

CREATE OR ALTER PROCEDURE UPDATE_CPU(
	@Id					INT,
	@Manufacturer		NVARCHAR(15),
	@Series				NVARCHAR(15),
	@Model				NVARCHAR(15),
	@Cores				INT,
	@MaxFrequency		DECIMAL(15, 2),
	@WorkingFrequency	DECIMAL(15, 2),
	@Architecture		NVARCHAR(15)
)
AS
BEGIN
	UPDATE CPU
	SET
		MANUFACTURER = ISNULL(@Manufacturer, MANUFACTURER),
		SERIES = ISNULL(@Series, SERIES),
		MODEL = ISNULL(@Model, MODEL),
		CORES = ISNULL(@Cores, CORES),
		MAX_FREQUENCY = ISNULL(@MaxFrequency, MAX_FREQUENCY),
		WORKING_FREQUENCY = ISNULL(@WorkingFrequency, WORKING_FREQUENCY),
		ARCHITECTURE = ISNULL(@Architecture, ARCHITECTURE)
	WHERE ID = @Id;
END;
GO

CREATE OR ALTER PROCEDURE DELETE_CPU(
	@Id		INT
)
AS
BEGIN
	DELETE FROM CPU
	WHERE ID = @Id;
END;
GO


CREATE OR ALTER PROCEDURE CREATE_PC(
	@Name				NVARCHAR(15),
	@Photo				IMAGE,
	@Type				NVARCHAR(15),
	@RamId				INT,
	@RomId				INT,
	@CpuId				INT
)
AS
BEGIN
	INSERT INTO PC(NAME, PHOTO, TYPE, RAM_ID, ROM_ID, CPU_ID)
	VALUES (@Name, @Photo, @Type, @RamId, @RomId, @CpuId);
END;
GO

CREATE OR ALTER PROCEDURE UPDATE_PC(
	@Id					INT,
	@Name				NVARCHAR(15),
	@Photo				IMAGE,
	@Type				NVARCHAR(15),
	@RamId				INT,
	@RomId				INT,
	@CpuId				INT
)
AS
BEGIN
	UPDATE PC
	SET
		NAME = ISNULL(@Name, NAME),
		PHOTO = ISNULL(@Photo, PHOTO),
		TYPE = ISNULL(@Type, TYPE),
		RAM_ID = ISNULL(@RamId, RAM_ID),
		ROM_ID = ISNULL(@RomId, ROM_ID),
		CPU_ID = ISNULL(@CpuId, CPU_ID)
	WHERE ID = @Id;
END;
GO

CREATE OR ALTER PROCEDURE DELETE_PC(
	@Id		INT
)
AS
BEGIN
	DELETE FROM PC
	WHERE ID = @Id;
END;
GO
