USE OOP_PC_INFO;
GO


CREATE TABLE RAM (
	ID		INT IDENTITY NOT NULL,
	TYPE	NVARCHAR(15) NOT NULL,
	VOLUME	DECIMAL(15, 2) NOT NULL,

	CONSTRAINT PK_RAM PRIMARY KEY (ID),
);
GO

CREATE TABLE ROM (
	ID		INT IDENTITY NOT NULL,
	TYPE	NVARCHAR(15) NOT NULL,
	VOLUME	DECIMAL(15, 2) NOT NULL,

	CONSTRAINT PK_ROM PRIMARY KEY (ID),
);
GO

CREATE TABLE CPU (
	ID					INT IDENTITY NOT NULL,
	MANUFACTURER		NVARCHAR(15) NOT NULL,
	SERIES				NVARCHAR(15) NOT NULL,
	MODEL				NVARCHAR(15) NOT NULL,
	CORES				INT NOT NULL,
	MAX_FREQUENCY		DECIMAL(15, 2) NOT NULL,
	WORKING_FREQUENCY	DECIMAL(15, 2) NOT NULL,
	ARCHITECTURE		NVARCHAR(15) NOT NULL,

	CONSTRAINT PK_CPU PRIMARY KEY (ID),
);
GO

CREATE TABLE PC (
	ID					INT IDENTITY NOT NULL,
	NAME				NVARCHAR(15) NOT NULL,
	PHOTO				IMAGE NOT NULL,
	TYPE				NVARCHAR(15) NOT NULL,
	RAM_ID				INT NOT NULL,
	ROM_ID				INT NOT NULL,
	CPU_ID				INT NOT NULL,

	CONSTRAINT PK_PC PRIMARY KEY (ID),
	CONSTRAINT FK_PC_RAM_ID FOREIGN KEY (RAM_ID) REFERENCES RAM(ID),
	CONSTRAINT FK_PC_ROM_ID FOREIGN KEY (ROM_ID) REFERENCES ROM(ID),
	CONSTRAINT FK_PC_CPU_ID FOREIGN KEY (CPU_ID) REFERENCES CPU(ID),
);
GO
